basePath: /api/
definitions:
  database.Error:
    properties:
      message:
        type: string
    type: object
  database.Point:
    properties:
      x:
        type: number
    type: object
  database.Spot:
    properties:
      coords:
        $ref: '#/definitions/database.Point'
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      handicap:
        type: boolean
      id:
        type: integer
      organizationID:
        type: integer
      updatedAt:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: This is the API for interacting with internal Tap-To-Park services
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://n3cd.io/terms/
  title: Tap-To-Park API
  version: "1.0"
paths: {}
swagger: "2.0"
